openapi: 3.0.1
info:
  title: Transaction Processing API
  version: v1
paths:
  /HealthCheck:
    get:
      tags:
        - HealthCheck
      responses:
        '200':
          description: Success
  /merchant-management/merchants:
    get:
      tags:
        - Merchant
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllMerchantsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Server Error
    post:
      tags:
        - Merchant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Merchant'
          text/json:
            schema:
              $ref: '#/components/schemas/Merchant'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Merchant'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Server Error
  '/merchant-management/merchants/{id}':
    get:
      tags:
        - Merchant
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMerchantResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Server Error
  /Transaction/direct-debits:
    get:
      tags:
        - Transaction
      parameters:
        - name: BankName
          in: query
          required: true
          schema:
            maxLength: 4
            minLength: 3
            type: string
        - name: DateToProcess
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectDebitsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Server Error
components:
  schemas:
    DirectDebitsResponse:
      type: object
      properties:
        directEntryAccounts:
          type: array
          items:
            $ref: '#/components/schemas/DirectEntryAccountModel'
          nullable: true
      additionalProperties: false
    DirectEntryAccountModel:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
        companyId:
          type: integer
          format: int64
        generateByCompanyId:
          type: boolean
        isBankInfoFromTrn:
          type: boolean
        isAccountLevelCredit:
          type: boolean
        isDisbursementLink:
          type: boolean
        isAdhoc:
          type: boolean
        trnTypesIncluded:
          type: string
          nullable: true
        isAggregatedAccountModule:
          type: boolean
        isIncludeCC:
          type: boolean
        isAutoPayments:
          type: boolean
        isWithBalancingRecord:
          type: boolean
        fromAccountId:
          type: integer
          format: int32
        amountCalculationType:
          type: integer
          format: int32
        templateTypeId:
          type: integer
          format: int32
        debitBankName:
          type: string
          nullable: true
        debitBankAssignedNumber:
          type: string
          nullable: true
        debitBankAssignedName:
          type: string
          nullable: true
        debitAccTitle:
          type: string
          nullable: true
        debitAccRouting:
          type: string
          nullable: true
        debitAccNo:
          type: string
          nullable: true
        debitRemitter:
          type: string
          nullable: true
        debitEntryDescriptor:
          type: string
          nullable: true
        debitLodgementRef:
          type: string
          nullable: true
        settlementTime:
          type: string
          nullable: true
        creditBankName:
          type: string
          nullable: true
        creditBankAssignedNumber:
          type: string
          nullable: true
        creditBankAssignedName:
          type: string
          nullable: true
        creditAccTitle:
          type: string
          nullable: true
        creditAccRouting:
          type: string
          nullable: true
        creditAccNo:
          type: string
          nullable: true
        creditRemitter:
          type: string
          nullable: true
        creditEntryDescriptor:
          type: string
          nullable: true
        creditLodgementRef:
          type: string
          nullable: true
        runNumber:
          type: integer
          format: int32
        directEntryTransactions:
          type: array
          items:
            $ref: '#/components/schemas/DirectEntryTransactionModel'
          nullable: true
      additionalProperties: false
    DirectEntryTransactionModel:
      type: object
      properties:
        cleanSpecialCharsOnAccTitle:
          type: boolean
        templateTypeId:
          type: integer
          format: int32
        trnId:
          type: integer
          format: int64
        trnType:
          type: integer
          format: int32
        accountId:
          type: integer
          format: int64
        companyId:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        customerNumber:
          type: string
          nullable: true
        amount:
          type: integer
          format: int64
        surcharge:
          type: integer
          format: int64
        custRef:
          type: string
          nullable: true
        receipt:
          type: string
          nullable: true
        sourceAccRouting:
          type: string
          nullable: true
        sourceAccNo:
          type: string
          nullable: true
        sourceAccTitle:
          type: string
          nullable: true
        destAccRouting:
          type: string
          nullable: true
        destAccNo:
          type: string
          nullable: true
        destAccTitle:
          type: string
          nullable: true
        aamPayment:
          type: boolean
        accountNumber:
          type: string
          nullable: true
        settlementDate:
          type: string
          nullable: true
        lodgementReference1:
          type: string
          nullable: true
        lodgementReference2:
          type: string
          nullable: true
        debitRemitter:
          type: string
          nullable: true
      additionalProperties: false
    GetAllMerchantsResponse:
      type: object
      properties:
        merchants:
          type: array
          items:
            $ref: '#/components/schemas/Merchant'
          nullable: true
      additionalProperties: false
    GetMerchantResponse:
      type: object
      properties:
        merchant:
          $ref: '#/components/schemas/Merchant'
      additionalProperties: false
    Merchant:
      type: object
      properties:
        merchantId:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        externalReference:
          type: string
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }